---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
    app.quarkus.io/commit-id: b1fecf1c0d19c3926cb2390260efba6537f30633
    app.quarkus.io/vcs-uri: https://github.com/quarkiverse/quarkus-playpen.git
    app.quarkus.io/build-timestamp: 2024-08-07 - 17:48:35 +0000
  labels:
    app.kubernetes.io/name: demo-rest-service-dev
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: demo-rest-service-dev
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: demo-rest-service-dev
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.11.0
    app.quarkus.io/commit-id: b1fecf1c0d19c3926cb2390260efba6537f30633
    app.quarkus.io/vcs-uri: https://github.com/quarkiverse/quarkus-playpen.git
    app.quarkus.io/build-timestamp: 2024-08-07 - 17:48:35 +0000
  labels:
    app.kubernetes.io/name: demo-rest-service-dev
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: demo-rest-service-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-rest-service-dev
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.11.0
        app.quarkus.io/commit-id: b1fecf1c0d19c3926cb2390260efba6537f30633
        app.quarkus.io/vcs-uri: https://github.com/quarkiverse/quarkus-playpen.git
        app.quarkus.io/build-timestamp: 2024-08-07 - 17:48:35 +0000
      labels:
        app.kubernetes.io/name: demo-rest-service-dev
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_LAUNCH_DEVMODE
              value: "true"
          image: docker.io/billburke/demo-rest-service-dev:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: demo-rest-service-dev
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
