---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: greeting-service
  name: greeting-service
spec:
  ports:
    - name: http
      nodePort: 30507
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: greeting-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: greeting-service
  name: greeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: greeting-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: greeting-service
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GREETING_ENV
              value: "Hello"
          image: docker.io/samples/greeting-service:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: greeting-service
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
