apiVersion: v1
kind: Pod
metadata:
  name: greeting-service-dev
  labels:
    name: greeting-service-dev
spec:
  containers:
    - image: docker.io/samples/greeting-service:1.0
      imagePullPolicy: IfNotPresent
      name: greeting-service-dev
      env:
        - name: QUARKUS_LAUNCH_DEVMODE
          value: "true"
        - name: GREETING_ENV
          value: "My Pod Greeting"
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP