---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/part-of: quarkus-playpen
  name: quarkus
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: quarkus-playpen
    app.kubernetes.io/name: quarkus-playpen-operator
  name: quarkus-playpen-operator
  namespace: quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpenconfig-cluster-role
rules:
  - apiGroups:
      - io.quarkiverse.playpen
    resources:
      - playpenconfigs
      - playpenconfigs/status
      - playpenconfigs/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playpen-cluster-role
rules:
  - apiGroups:
      - io.quarkiverse.playpen
    resources:
      - playpens
      - playpens/status
      - playpens/finalizers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpen-operator-cluster-role
rules:
  - apiGroups:
      - ""
      - apps
    resources:
      - services
      - deployments
      - secrets
      - serviceaccounts
      - rolebindings
    verbs:
      - get
      - list
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - ""
      - route.openshift.io
    resources:
      - routes
    verbs:
      - get
      - list
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - patch
      - update
      - create
      - delete
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - get
      - list
      - patch
      - update
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpen-proxy-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - patch
      - update
      - create
      - delete
      - watch
  - apiGroups:
      - ""
      - apps
    resources:
      - services
      - deployments
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: quarkus-playpen
  annotations:
    app.dekorate.io/commit-id: 2bb0280275625c12023981fc89a487438c12dd04
  name: josdk-crd-validating-cluster-role
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpen-crd-validating-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: josdk-crd-validating-cluster-role
subjects:
  - kind: ServiceAccount
    name: quarkus-playpen-operator
    namespace: quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpenconfig-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: playpenconfig-cluster-role
subjects:
  - kind: ServiceAccount
    name: quarkus-playpen-operator
    namespace: quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpen-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: playpen-cluster-role
subjects:
  - kind: ServiceAccount
    name: quarkus-playpen-operator
    namespace: quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/part-of: quarkus-playpen
  name: playpen-operator-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: playpen-operator-cluster-role
subjects:
  - kind: ServiceAccount
    name: quarkus-playpen-operator
    namespace: quarkus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/part-of: quarkus-playpen
  name: quarkus-playpen-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: quarkus-playpen-operator
    namespace: quarkus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/version: 999-SNAPSHOT
    app.kubernetes.io/part-of: quarkus-playpen
  name: quarkus-playpen-operator
  namespace: quarkus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-playpen-operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: quarkus-playpen-operator
    app.kubernetes.io/version: 999-SNAPSHOT
    app.kubernetes.io/part-of: quarkus-playpen
  name: quarkus-playpen-operator
  namespace: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-playpen-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 999-SNAPSHOT
        app.kubernetes.io/name: quarkus-playpen-operator
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PROXY_IMAGE
              value: "docker.io/quarkus-playpen/playpen-proxy:999-SNAPSHOT"
            - name: PROXY_IMAGEPULLPOLICY
              value: "IfNotPresent"
            - name: REMOTE_PLAYPEN_IMAGE
              value: "docker.io/quarkus-playpen/remote-quarkus-playpen:latest"
            - name: REMOTE_PLAYPEN_IMAGEPULLPOLICY
              value: "IfNotPresent"
          image: docker.io/quarkus-playpen/playpen-operator:999-SNAPSHOT
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: quarkus-playpen-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: quarkus-playpen-operator
